#!/usr/bin/env sh

set -e

pnpm run prettier:lint .
pnpm run markdown:lint .

docker compose run --rm -T hadolint hadolint docker/golang/Dockerfile
docker compose run --rm -T hadolint hadolint docker/hadolint/Dockerfile

docker compose run --rm -T shellcheck -x ./.husky/pre-commit
docker compose run --rm -T shellcheck -x ./.husky/pre-push
docker compose run --rm -T shellcheck -x ./.husky/commit-msg

docker compose run --rm -T golang go mod download
docker compose run --rm -T golang go build -v

docker compose run --rm -T golang golangci-lint run
docker compose run --rm -T golang go test -cover ./...
